package com.openclaw.clawagent

import android.content.Context
import android.net.ConnectivityManager
import android.net.NetworkCapabilities
import androidx.test.core.app.ApplicationProvider
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.mockito.Mockito
import org.mockito.Mockito.`when`
import org.mockito.kotlin.mock

/**
 * Instrumented tests that run on an Android device or emulator.
 *
 * These tests verify UI-adjacent behavior that requires the Android runtime:
 * - ViewBinding inflation
 * - RecyclerView adapter operations
 * - Clipboard interactions
 * - SharedPreferences history round-trip
 *
 * Run with: ./gradlew connectedDebugAndroidTest
 */
class MainActivityInstrumentedTest {

    private lateinit var context: Context

    @Before
    fun setUp() {
        context = ApplicationProvider.getApplicationContext()
    }

    // ── ViewBinding ───────────────────────────────────────────────

    @Test
    fun activityMainBinding_inflates() {
        // We cannot launch Activity here without an instrumentation runner,
        // but we can verify the layout resource exists and the binding class
        // is generated by inflating with the application context.
        val binding = com.openclaw.clawagent.databinding.ActivityMainBinding
            .inflate(context.getSystemService(Context.LAYOUT_INFLATER_SERVICE) as android.view.LayoutInflater)
        assertTrue(binding.root is android.view.View)
    }

    // ── ChatMessage ───────────────────────────────────────────────

    @Test
    fun chatMessage_roles_are_stored_correctly() {
        val userMsg = ChatMessage("user", "test input")
        val assistantMsg = ChatMessage("assistant", "test output")

        assertEquals("user", userMsg.role)
        assertEquals("assistant", assistantMsg.role)
        assertEquals("test input", userMsg.content)
        assertEquals("test output", assistantMsg.content)
    }

    @Test
    fun chatMessage_empty_content_is_valid() {
        val msg = ChatMessage("assistant", "")
        assertEquals("", msg.content)
        assertEquals("assistant", msg.role)
    }

    // ── History SharedPreferences round-trip ──────────────────────

    @Test
    fun history_persists_and_restores_across_process_boundary() {
        val prefs = context.getSharedPreferences("claw_history_inst", Context.MODE_PRIVATE)
        val messages = listOf(
            ChatMessage("user", "Hello"),
            ChatMessage("assistant", "Hi there!"),
            ChatMessage("user", "How are you?"),
            ChatMessage("assistant", "I'm good, thanks!"),
        )

        // Serialize
        val json = org.json.JSONArray()
        messages.forEach {
            json.put(org.json.JSONObject().apply {
                put("role", it.role)
                put("content", it.content)
            })
        })
        prefs.edit().putString("history", json.toString()).commit()

        // Read back in a fresh editor (simulates process restart)
        val loaded = prefs.getString("history", null)
        assertTrue(loaded != null)

        val restored = mutableListOf<ChatMessage>()
        val arr = org.json.JSONArray(loaded)
        for (i in 0 until arr.length()) {
            val obj = arr.getJSONObject(i)
            restored.add(ChatMessage(obj.getString("role"), obj.getString("content")))
        }

        assertEquals(messages.size, restored.size)
        for (j in messages.indices) {
            assertEquals(messages[j].role, restored[j].role)
            assertEquals(messages[j].content, restored[j].content)
        }

        // Clean up
        prefs.edit().remove("history").commit()
    }

    // ── Settings SharedPreferences round-trip ─────────────────────

    @Test
    fun settings_persist_all_fields() {
        val prefs = context.getSharedPreferences("claw_settings_inst", Context.MODE_PRIVATE)
        prefs.edit()
            .putString("provider_id", "stepfun")
            .putString("model", "step-3.7-flash")
            .putString("api_endpoint", "https://api.stepfun.com/v1")
            .putBoolean("keep_context", true)
            .putBoolean("stream", false)
            .putInt("context_limit", 50)
            .putString("system_prompt", "You are helpful.")
            .putBoolean("agent_mode", true)
            .commit()

        assertEquals("stepfun", prefs.getString("provider_id", ""))
        assertEquals("step-3.7-flash", prefs.getString("model", ""))
        assertEquals("https://api.stepfun.com/v1", prefs.getString("api_endpoint", ""))
        assertTrue(prefs.getBoolean("keep_context", false))
        assertFalse(prefs.getBoolean("stream", true))
        assertEquals(50, prefs.getInt("context_limit", 20))
        assertEquals("You are helpful.", prefs.getString("system_prompt", ""))
        assertTrue(prefs.getBoolean("agent_mode", false))

        prefs.edit().clear().commit()
    }

    // ── Message list operations ───────────────────────────────────

    @Test
    fun messageList_add_and_clear_works() {
        val messages = mutableListOf<ChatMessage>()
        assertTrue(messages.isEmpty())

        messages.add(ChatMessage("user", "Q1"))
        messages.add(ChatMessage("assistant", "A1"))
        assertEquals(2, messages.size)

        messages.clear()
        assertTrue(messages.isEmpty())
    }

    @Test
    fun messageList_takeLast_respects_cap() {
        val messages = mutableListOf<ChatMessage>()
        repeat(500) { i ->
            messages.add(ChatMessage("user", "msg_$i"))
        }
        val capped = messages.takeLast(300)
        assertEquals(300, capped.size)
        assertEquals("msg_200", capped[0].content)
        assertEquals("msg_499", capped[499].content)
    }

    // ── Request history builder ───────────────────────────────────

    @Test
    fun requestHistory_systemPrompt_prepended_when_set() {
        val history = buildRequestHistory(
            userText = "Hi",
            pastMessages = emptyList(),
            systemPrompt = "Be brief.",
            keepContext = true,
            contextLimit = 0,
        )
        assertEquals(2, history.size)
        assertEquals("system", history[0].role)
        assertEquals("Be brief.", history[0].content)
        assertEquals("user", history[1].role)
        assertEquals("Hi", history[1].content)
    }

    @Test
    fun requestHistory_noContext_when_disabled() {
        val history = buildRequestHistory(
            userText = "Hi",
            pastMessages = listOf(ChatMessage("user", "Old"), ChatMessage("assistant", "Old answer")),
            systemPrompt = "",
            keepContext = false,
            contextLimit = 0,
        )
        assertEquals(1, history.size)
        assertEquals("Hi", history[0].content)
    }

    @Test
    fun requestHistory_truncates_to_limit() {
        val past = List(20) { i -> ChatMessage("user", "m$i") }
        val history = buildRequestHistory(
            userText = "New",
            pastMessages = past,
            systemPrompt = "",
            keepContext = true,
            contextLimit = 5,
        )
        // 5 context + 1 user turn
        assertEquals(6, history.size)
        assertEquals("m15", history[0].content)
        assertEquals("m19", history[4].content)
        assertEquals("New", history[5].content)
    }

    // ── Helpers ───────────────────────────────────────────────────

    private fun buildRequestHistory(
        userText: String,
        pastMessages: List<ChatMessage>,
        systemPrompt: String,
        keepContext: Boolean,
        contextLimit: Int,
    ): List<com.openclaw.clawagent.provider.ChatService.Message> {
        val systemMsgs = systemPrompt.trim().takeIf { it.isNotEmpty() }
            ?.let { listOf(com.openclaw.clawagent.provider.ChatService.Message("system", it)) }
            ?: emptyList()
        if (!keepContext) {
            return systemMsgs + listOf(com.openclaw.clawagent.provider.ChatService.Message("user", userText))
        }
        val base = pastMessages.map { com.openclaw.clawagent.provider.ChatService.Message(it.role, it.content) }
        val limited = if (contextLimit > 0) base.takeLast(contextLimit) else base
        return systemMsgs + limited + listOf(com.openclaw.clawagent.provider.ChatService.Message("user", userText))
    }
}
